apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode1-frontend
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: episode1-frontend
  template:
    metadata:
      labels:
        app: episode1-frontend
    spec:
      containers:
      - name: episode1-frontend
        image: notabd/episode1-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
