apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode1-backend
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: episode1-backend
  template:
    metadata:
      labels:
        app: episode1-backend
    spec:
      containers:
      - name: episode1-backend
        image: notabd/episode1-backend:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: NODE_ENV
          value: "production"
