apiVersion: v1
kind: Service
metadata:
  name: episode5-frontend-service
  namespace: development
spec:
  selector:
    app: episode5-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
