apiVersion: v1
kind: Service
metadata:
  name: episode5-backend-service
  namespace: development
spec:
  selector:
    app: episode5-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
