apiVersion: v1
kind: Service
metadata:
  name: episode4-backend-service
  namespace: development
spec:
  selector:
    app: episode4-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
