apiVersion: v1
kind: Service
metadata:
  name: episode4-frontend-service
  namespace: development
spec:
  selector:
    app: episode4-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
