apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode4-frontend
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: episode4-frontend
  template:
    metadata:
      labels:
        app: episode4-frontend
    spec:
      containers:
      - name: episode4-frontend
        image: notabd/episode4-frontend:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
